name: Deploy to WebServer

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: random ID を生成
        run: |
            echo "RANDOM_ID=$(uuidgen)" >> $GITHUB_ENV;
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV;
            echo "SRC_PATH=/tmp/${{ github.event.repository.name }}.tar.gz" >> $GITHUB_ENV;

      - name: ソースコードの Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.DEPLOY_BRANCH }}

      - name: ソースコードを圧縮
        run: |
            cd ${{ vars.DEPLOY_DIR }} ;
            mkdir /tmp/${{ env.RANDOM_ID }};
            tar -zcf /tmp/${{ env.RANDOM_ID }}/${{ env.REPO_NAME }}-${{ env.RANDOM_ID }}.tar.gz .;
            ls -la /tmp/${{ env.RANDOM_ID }}/${{ env.REPO_NAME }}-${{ env.RANDOM_ID }}.tar.gz

      - name: SFTP プロトコルでファイル転送
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          forceUpload: true
          localDir: "/tmp/${{ env.RANDOM_ID }}/"
          remoteDir: "/tmp/${{ env.RANDOM_ID }}/"

      - name: リモートサーバに配置処理をする
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            hostname;
            cd /srv/www/html;
            mkdir -p ${{ env.REPO_NAME }}/htdocs;
            cd ${{ env.REPO_NAME }}/htdocs;
            tar zxf /tmp/${{ env.RANDOM_ID }}/${{ env.REPO_NAME }}-${{ env.RANDOM_ID }}.tar.gz
